/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = iimmpact.Client.SwaggerDateConverter;

namespace iimmpact.Model
{
    /// <summary>
    /// CallbackUrlResponse
    /// </summary>
    [DataContract]
    public partial class CallbackUrlResponse :  IEquatable<CallbackUrlResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallbackUrlResponse" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="metadata">metadata.</param>
        public CallbackUrlResponse(CallbackUrlResponseData data = default(CallbackUrlResponseData), CallbackUrlResponseMetadata metadata = default(CallbackUrlResponseMetadata))
        {
            this.data = data;
            this.@metadata = @metadata;
        }
        
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public CallbackUrlResponseData data { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name="@metadata", EmitDefaultValue=false)]
        public CallbackUrlResponseMetadata @metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallbackUrlResponse {\n");
            sb.Append("  data: ").Append(data).Append("\n");
            sb.Append("  @metadata: ").Append(@metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CallbackUrlResponse);
        }

        /// <summary>
        /// Returns true if CallbackUrlResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CallbackUrlResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallbackUrlResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.data == input.data ||
                    (this.data != null &&
                    this.data.Equals(input.data))
                ) && 
                (
                    this.@metadata == input.@metadata ||
                    (this.@metadata != null &&
                    this.@metadata.Equals(input.@metadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.data != null)
                    hashCode = hashCode * 59 + this.data.GetHashCode();
                if (this.@metadata != null)
                    hashCode = hashCode * 59 + this.@metadata.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
