/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = iimmpact.Client.SwaggerDateConverter;

namespace iimmpact.Model
{
    /// <summary>
    /// LowBalanceWarningResponseData
    /// </summary>
    [DataContract]
    public partial class LowBalanceWarningResponseData :  IEquatable<LowBalanceWarningResponseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LowBalanceWarningResponseData" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="email">email.</param>
        /// <param name="balanceThreshold">balanceThreshold.</param>
        /// <param name="note">note.</param>
        public LowBalanceWarningResponseData(string status = default(string), string email = default(string), string balanceThreshold = default(string), string note = default(string))
        {
            this.Status = status;
            this.Email = email;
            this.BalanceThreshold = balanceThreshold;
            this.Note = note;
        }
        
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name="Email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets BalanceThreshold
        /// </summary>
        [DataMember(Name="BalanceThreshold", EmitDefaultValue=false)]
        public string BalanceThreshold { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember(Name="Note", EmitDefaultValue=false)]
        public string Note { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LowBalanceWarningResponseData {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  BalanceThreshold: ").Append(BalanceThreshold).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LowBalanceWarningResponseData);
        }

        /// <summary>
        /// Returns true if LowBalanceWarningResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of LowBalanceWarningResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LowBalanceWarningResponseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.BalanceThreshold == input.BalanceThreshold ||
                    (this.BalanceThreshold != null &&
                    this.BalanceThreshold.Equals(input.BalanceThreshold))
                ) && 
                (
                    this.Note == input.Note ||
                    (this.Note != null &&
                    this.Note.Equals(input.Note))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.BalanceThreshold != null)
                    hashCode = hashCode * 59 + this.BalanceThreshold.GetHashCode();
                if (this.Note != null)
                    hashCode = hashCode * 59 + this.Note.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
