/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = iimmpact.Client.SwaggerDateConverter;

namespace iimmpact.Model
{
    /// <summary>
    /// NetworkStatusResponseData
    /// </summary>
    [DataContract]
    public partial class NetworkStatusResponseData :  IEquatable<NetworkStatusResponseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkStatusResponseData" /> class.
        /// </summary>
        /// <param name="productCode">productCode.</param>
        /// <param name="productName">productName.</param>
        /// <param name="productImg">productImg.</param>
        /// <param name="networkStatus">networkStatus.</param>
        public NetworkStatusResponseData(string productCode = default(string), string productName = default(string), string productImg = default(string), string networkStatus = default(string))
        {
            this.ProductCode = productCode;
            this.ProductName = productName;
            this.ProductImg = productImg;
            this.NetworkStatus = networkStatus;
        }
        
        /// <summary>
        /// Gets or Sets ProductCode
        /// </summary>
        [DataMember(Name="product_code", EmitDefaultValue=false)]
        public string ProductCode { get; set; }

        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name="product_name", EmitDefaultValue=false)]
        public string ProductName { get; set; }

        /// <summary>
        /// Gets or Sets ProductImg
        /// </summary>
        [DataMember(Name="product_img", EmitDefaultValue=false)]
        public string ProductImg { get; set; }

        /// <summary>
        /// Gets or Sets NetworkStatus
        /// </summary>
        [DataMember(Name="network_status", EmitDefaultValue=false)]
        public string NetworkStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NetworkStatusResponseData {\n");
            sb.Append("  ProductCode: ").Append(ProductCode).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  ProductImg: ").Append(ProductImg).Append("\n");
            sb.Append("  NetworkStatus: ").Append(NetworkStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NetworkStatusResponseData);
        }

        /// <summary>
        /// Returns true if NetworkStatusResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of NetworkStatusResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NetworkStatusResponseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProductCode == input.ProductCode ||
                    (this.ProductCode != null &&
                    this.ProductCode.Equals(input.ProductCode))
                ) && 
                (
                    this.ProductName == input.ProductName ||
                    (this.ProductName != null &&
                    this.ProductName.Equals(input.ProductName))
                ) && 
                (
                    this.ProductImg == input.ProductImg ||
                    (this.ProductImg != null &&
                    this.ProductImg.Equals(input.ProductImg))
                ) && 
                (
                    this.NetworkStatus == input.NetworkStatus ||
                    (this.NetworkStatus != null &&
                    this.NetworkStatus.Equals(input.NetworkStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductCode != null)
                    hashCode = hashCode * 59 + this.ProductCode.GetHashCode();
                if (this.ProductName != null)
                    hashCode = hashCode * 59 + this.ProductName.GetHashCode();
                if (this.ProductImg != null)
                    hashCode = hashCode * 59 + this.ProductImg.GetHashCode();
                if (this.NetworkStatus != null)
                    hashCode = hashCode * 59 + this.NetworkStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
