/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using iimmpact.Client;
using iimmpact.Model;

namespace iimmpact.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILowBalanceWarningApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LowBalanceWarningResponse</returns>
        LowBalanceWarningResponse V1LowBalanceThresholdGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LowBalanceWarningResponse</returns>
        ApiResponse<LowBalanceWarningResponse> V1LowBalanceThresholdGetWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>LowBalanceWarningResponse</returns>
        LowBalanceWarningResponse V1LowBalanceThresholdPost (string amount);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>ApiResponse of LowBalanceWarningResponse</returns>
        ApiResponse<LowBalanceWarningResponse> V1LowBalanceThresholdPostWithHttpInfo (string amount);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LowBalanceWarningResponse</returns>
        System.Threading.Tasks.Task<LowBalanceWarningResponse> V1LowBalanceThresholdGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LowBalanceWarningResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LowBalanceWarningResponse>> V1LowBalanceThresholdGetAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>Task of LowBalanceWarningResponse</returns>
        System.Threading.Tasks.Task<LowBalanceWarningResponse> V1LowBalanceThresholdPostAsync (string amount);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>Task of ApiResponse (LowBalanceWarningResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LowBalanceWarningResponse>> V1LowBalanceThresholdPostAsyncWithHttpInfo (string amount);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LowBalanceWarningApi : ILowBalanceWarningApi
    {
        private iimmpact.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LowBalanceWarningApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LowBalanceWarningApi(String basePath)
        {
            this.Configuration = new iimmpact.Client.Configuration { BasePath = basePath };

            ExceptionFactory = iimmpact.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LowBalanceWarningApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LowBalanceWarningApi(iimmpact.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = iimmpact.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = iimmpact.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public iimmpact.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public iimmpact.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LowBalanceWarningResponse</returns>
        public LowBalanceWarningResponse V1LowBalanceThresholdGet ()
        {
             ApiResponse<LowBalanceWarningResponse> localVarResponse = V1LowBalanceThresholdGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LowBalanceWarningResponse</returns>
        public ApiResponse< LowBalanceWarningResponse > V1LowBalanceThresholdGetWithHttpInfo ()
        {

            var localVarPath = "/v1/low-balance-threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (SSO) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1LowBalanceThresholdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LowBalanceWarningResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LowBalanceWarningResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LowBalanceWarningResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LowBalanceWarningResponse</returns>
        public async System.Threading.Tasks.Task<LowBalanceWarningResponse> V1LowBalanceThresholdGetAsync ()
        {
             ApiResponse<LowBalanceWarningResponse> localVarResponse = await V1LowBalanceThresholdGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LowBalanceWarningResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LowBalanceWarningResponse>> V1LowBalanceThresholdGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/v1/low-balance-threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (SSO) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1LowBalanceThresholdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LowBalanceWarningResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LowBalanceWarningResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LowBalanceWarningResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>LowBalanceWarningResponse</returns>
        public LowBalanceWarningResponse V1LowBalanceThresholdPost (string amount)
        {
             ApiResponse<LowBalanceWarningResponse> localVarResponse = V1LowBalanceThresholdPostWithHttpInfo(amount);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>ApiResponse of LowBalanceWarningResponse</returns>
        public ApiResponse< LowBalanceWarningResponse > V1LowBalanceThresholdPostWithHttpInfo (string amount)
        {
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling LowBalanceWarningApi->V1LowBalanceThresholdPost");

            var localVarPath = "/v1/low-balance-threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (amount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter

            // authentication (SSO) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1LowBalanceThresholdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LowBalanceWarningResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LowBalanceWarningResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LowBalanceWarningResponse)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>Task of LowBalanceWarningResponse</returns>
        public async System.Threading.Tasks.Task<LowBalanceWarningResponse> V1LowBalanceThresholdPostAsync (string amount)
        {
             ApiResponse<LowBalanceWarningResponse> localVarResponse = await V1LowBalanceThresholdPostAsyncWithHttpInfo(amount);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="iimmpact.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="amount"></param>
        /// <returns>Task of ApiResponse (LowBalanceWarningResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LowBalanceWarningResponse>> V1LowBalanceThresholdPostAsyncWithHttpInfo (string amount)
        {
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling LowBalanceWarningApi->V1LowBalanceThresholdPost");

            var localVarPath = "/v1/low-balance-threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (amount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter

            // authentication (SSO) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1LowBalanceThresholdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LowBalanceWarningResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LowBalanceWarningResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LowBalanceWarningResponse)));
        }

    }
}
