/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using iimmpact.Client;
using iimmpact.Api;
using iimmpact.Model;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing AuthorizationTokenApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AuthorizationTokenApiTests
    {
        private AuthorizationTokenApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AuthorizationTokenApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthorizationTokenApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AuthorizationTokenApi
            //Assert.IsInstanceOfType(typeof(AuthorizationTokenApi), instance, "instance is a AuthorizationTokenApi");
        }

        
        /// <summary>
        /// Test V1TokenPost
        /// </summary>
        [Test]
        public void V1TokenPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TokenRequest tokenRequest = null;
            //var response = instance.V1TokenPost(tokenRequest);
            //Assert.IsInstanceOf<TokenResponse> (response, "response is TokenResponse");
        }
        
        /// <summary>
        /// Test V1TokenRefreshPost
        /// </summary>
        [Test]
        public void V1TokenRefreshPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RefreshTokenRequest refreshTokenRequest = null;
            //var response = instance.V1TokenRefreshPost(refreshTokenRequest);
            //Assert.IsInstanceOf<RefreshTokenResponse> (response, "response is RefreshTokenResponse");
        }
        
    }

}
