/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using iimmpact.Client;
using iimmpact.Api;
using iimmpact.Model;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing LowBalanceWarningApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LowBalanceWarningApiTests
    {
        private LowBalanceWarningApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LowBalanceWarningApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LowBalanceWarningApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LowBalanceWarningApi
            //Assert.IsInstanceOfType(typeof(LowBalanceWarningApi), instance, "instance is a LowBalanceWarningApi");
        }

        
        /// <summary>
        /// Test V1LowBalanceThresholdGet
        /// </summary>
        [Test]
        public void V1LowBalanceThresholdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1LowBalanceThresholdGet();
            //Assert.IsInstanceOf<LowBalanceWarningResponse> (response, "response is LowBalanceWarningResponse");
        }
        
        /// <summary>
        /// Test V1LowBalanceThresholdPost
        /// </summary>
        [Test]
        public void V1LowBalanceThresholdPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string amount = null;
            //var response = instance.V1LowBalanceThresholdPost(amount);
            //Assert.IsInstanceOf<LowBalanceWarningResponse> (response, "response is LowBalanceWarningResponse");
        }
        
    }

}
