/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using iimmpact.Client;
using iimmpact.Api;
using iimmpact.Model;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing ServicesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ServicesApiTests
    {
        private ServicesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ServicesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServicesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ServicesApi
            //Assert.IsInstanceOfType(typeof(ServicesApi), instance, "instance is a ServicesApi");
        }

        
        /// <summary>
        /// Test V1BillPresentmentGet
        /// </summary>
        [Test]
        public void V1BillPresentmentGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string account = null;
            //string accountName = null;
            //string product = null;
            //var response = instance.V1BillPresentmentGet(account, accountName, product);
            //Assert.IsInstanceOf<BillPresentmentResponse> (response, "response is BillPresentmentResponse");
        }
        
        /// <summary>
        /// Test V1NetworkstatusGet
        /// </summary>
        [Test]
        public void V1NetworkstatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string product = null;
            //var response = instance.V1NetworkstatusGet(product);
            //Assert.IsInstanceOf<NetworkStatusResponse> (response, "response is NetworkStatusResponse");
        }
        
        /// <summary>
        /// Test V1TopupPost
        /// </summary>
        [Test]
        public void V1TopupPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TopupRequest topupRequest = null;
            //var response = instance.V1TopupPost(topupRequest);
            //Assert.IsInstanceOf<TopupResponse> (response, "response is TopupResponse");
        }
        
    }

}
