/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using iimmpact.Client;
using iimmpact.Api;
using iimmpact.Model;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing TransactionHistoryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TransactionHistoryApiTests
    {
        private TransactionHistoryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TransactionHistoryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionHistoryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TransactionHistoryApi
            //Assert.IsInstanceOfType(typeof(TransactionHistoryApi), instance, "instance is a TransactionHistoryApi");
        }

        
        /// <summary>
        /// Test V1BalanceStatementGet
        /// </summary>
        [Test]
        public void V1BalanceStatementGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string date = null;
            //string limit = null;
            //string remarks = null;
            //string sort = null;
            //string type = null;
            //string direction = null;
            //string page = null;
            //string amount = null;
            //var response = instance.V1BalanceStatementGet(date, limit, remarks, sort, type, direction, page, amount);
            //Assert.IsInstanceOf<BalanceStatementResponse> (response, "response is BalanceStatementResponse");
        }
        
        /// <summary>
        /// Test V1TransactionsGet
        /// </summary>
        [Test]
        public void V1TransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string date = null;
            //string refid = null;
            //string limit = null;
            //string sort = null;
            //string offset = null;
            //string direction = null;
            //string status = null;
            //string account = null;
            //string acceptEncoding = null;
            //string sn = null;
            //string product = null;
            //var response = instance.V1TransactionsGet(date, refid, limit, sort, offset, direction, status, account, acceptEncoding, sn, product);
            //Assert.IsInstanceOf<TransactionsResponse> (response, "response is TransactionsResponse");
        }
        
    }

}
