/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing BillPresentmentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillPresentmentResponseTests
    {
        // TODO uncomment below to declare an instance variable for BillPresentmentResponse
        //private BillPresentmentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillPresentmentResponse
            //instance = new BillPresentmentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillPresentmentResponse
        /// </summary>
        [Test]
        public void BillPresentmentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillPresentmentResponse
            //Assert.IsInstanceOfType<BillPresentmentResponse> (instance, "variable 'instance' is a BillPresentmentResponse");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
