/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing CallbackUrlResponseMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallbackUrlResponseMetadataTests
    {
        // TODO uncomment below to declare an instance variable for CallbackUrlResponseMetadata
        //private CallbackUrlResponseMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallbackUrlResponseMetadata
            //instance = new CallbackUrlResponseMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallbackUrlResponseMetadata
        /// </summary>
        [Test]
        public void CallbackUrlResponseMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallbackUrlResponseMetadata
            //Assert.IsInstanceOfType<CallbackUrlResponseMetadata> (instance, "variable 'instance' is a CallbackUrlResponseMetadata");
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }

    }

}
