/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing ChangePasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangePasswordRequestTests
    {
        // TODO uncomment below to declare an instance variable for ChangePasswordRequest
        //private ChangePasswordRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangePasswordRequest
            //instance = new ChangePasswordRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangePasswordRequest
        /// </summary>
        [Test]
        public void ChangePasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangePasswordRequest
            //Assert.IsInstanceOfType<ChangePasswordRequest> (instance, "variable 'instance' is a ChangePasswordRequest");
        }


        /// <summary>
        /// Test the property 'OldPassword'
        /// </summary>
        [Test]
        public void OldPasswordTest()
        {
            // TODO unit test for the property 'OldPassword'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

    }

}
