/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing DrivingLicenseResponeInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DrivingLicenseResponeInnerTests
    {
        // TODO uncomment below to declare an instance variable for DrivingLicenseResponeInner
        //private DrivingLicenseResponeInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DrivingLicenseResponeInner
            //instance = new DrivingLicenseResponeInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DrivingLicenseResponeInner
        /// </summary>
        [Test]
        public void DrivingLicenseResponeInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DrivingLicenseResponeInner
            //Assert.IsInstanceOfType<DrivingLicenseResponeInner> (instance, "variable 'instance' is a DrivingLicenseResponeInner");
        }


        /// <summary>
        /// Test the property 'TypeOfDrivingLicense'
        /// </summary>
        [Test]
        public void TypeOfDrivingLicenseTest()
        {
            // TODO unit test for the property 'TypeOfDrivingLicense'
        }
        /// <summary>
        /// Test the property 'DateOfCommencement'
        /// </summary>
        [Test]
        public void DateOfCommencementTest()
        {
            // TODO unit test for the property 'DateOfCommencement'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Test]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }

    }

}
