/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing LowBalanceWarningResponseMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LowBalanceWarningResponseMetadataTests
    {
        // TODO uncomment below to declare an instance variable for LowBalanceWarningResponseMetadata
        //private LowBalanceWarningResponseMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LowBalanceWarningResponseMetadata
            //instance = new LowBalanceWarningResponseMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LowBalanceWarningResponseMetadata
        /// </summary>
        [Test]
        public void LowBalanceWarningResponseMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LowBalanceWarningResponseMetadata
            //Assert.IsInstanceOfType<LowBalanceWarningResponseMetadata> (instance, "variable 'instance' is a LowBalanceWarningResponseMetadata");
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }

    }

}
