/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing NewPasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewPasswordRequestTests
    {
        // TODO uncomment below to declare an instance variable for NewPasswordRequest
        //private NewPasswordRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewPasswordRequest
            //instance = new NewPasswordRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewPasswordRequest
        /// </summary>
        [Test]
        public void NewPasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewPasswordRequest
            //Assert.IsInstanceOfType<NewPasswordRequest> (instance, "variable 'instance' is a NewPasswordRequest");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'OldPassword'
        /// </summary>
        [Test]
        public void OldPasswordTest()
        {
            // TODO unit test for the property 'OldPassword'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Test]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }

    }

}
