/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing TransactionsResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionsResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for TransactionsResponseData
        //private TransactionsResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionsResponseData
            //instance = new TransactionsResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionsResponseData
        /// </summary>
        [Test]
        public void TransactionsResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionsResponseData
            //Assert.IsInstanceOfType<TransactionsResponseData> (instance, "variable 'instance' is a TransactionsResponseData");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'EntryDate'
        /// </summary>
        [Test]
        public void EntryDateTest()
        {
            // TODO unit test for the property 'EntryDate'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Test]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'TopupNumber'
        /// </summary>
        [Test]
        public void TopupNumberTest()
        {
            // TODO unit test for the property 'TopupNumber'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'MemberId'
        /// </summary>
        [Test]
        public void MemberIdTest()
        {
            // TODO unit test for the property 'MemberId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Sn'
        /// </summary>
        [Test]
        public void SnTest()
        {
            // TODO unit test for the property 'Sn'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Test]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'RefId'
        /// </summary>
        [Test]
        public void RefIdTest()
        {
            // TODO unit test for the property 'RefId'
        }

    }

}
