/* 
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iimmpact.Api;
using iimmpact.Model;
using iimmpact.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iimmpact.Test
{
    /// <summary>
    ///  Class for testing TransactionsResponseBalance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionsResponseBalanceTests
    {
        // TODO uncomment below to declare an instance variable for TransactionsResponseBalance
        //private TransactionsResponseBalance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionsResponseBalance
            //instance = new TransactionsResponseBalance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionsResponseBalance
        /// </summary>
        [Test]
        public void TransactionsResponseBalanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionsResponseBalance
            //Assert.IsInstanceOfType<TransactionsResponseBalance> (instance, "variable 'instance' is a TransactionsResponseBalance");
        }


        /// <summary>
        /// Test the property 'Prev'
        /// </summary>
        [Test]
        public void PrevTest()
        {
            // TODO unit test for the property 'Prev'
        }
        /// <summary>
        /// Test the property 'New'
        /// </summary>
        [Test]
        public void NewTest()
        {
            // TODO unit test for the property 'New'
        }

    }

}
